### ISSUE TITLE
Active Development?

### ISSUE THREAD

**Issue by wbrawner** [seizonsenryaku/HayaiLauncher#107]
Hey, just curious to see if the app is stilll in active development. I'd love to contribute but I haven't seen any recent commits so I figured I'd check before forking or submitting PRs :)

Cheers

**Comment by avuton** [comment]
The best way to check this is to check the [Insights/Network](https://github.com/seizonsenryaku/HayaiLauncher/network) Github feature.  Also, for more information on this, see PR #104.

**Comment by wbrawner** [comment]
I did take a look at this, but I don't consider a lack of commits a lack of active development per se. Your PR however does seem to be a clear indication of the lack of active development though. Do you have any plans to release your fork to the Google Play Store or FDroid?

**Comment by wbrawner** [comment]
Disregard, saw for myself. I'll close this issue
