### ISSUE TITLE
still active?

### ISSUE THREAD

**Issue by IzzySoft** [seizonsenryaku/HayaiLauncher#108]
Just wondering whether this project is still active. If not, you might wish to achive it (that marks it as inactive and read-only; you can "unarchive" it any time) after pointing to [its successor](https://github.com/KeikaiLauncher/KeikaiLauncher) from the README.

What'd you say, @edgarvperes?

**Comment by avuton** [comment]
This road has been traveled down [before](https://github.com/edgarvperes/HayaiLauncher/issues/107).

**Comment by IzzySoft** [comment]
@avuton Ah, yes. And that PR is still unprocessed – plus Last updated Jul 18, 2017 accoring to Github. Guess that should answer my first question. Still, if no longer maintained the project should be archved, to make the status clear (and no guess-work) – hence I'll leave this issue open. Though I somehow doubt @edgarvperes will react on it.
