### ISSUE TITLE
define action button actions

### ISSUE THREAD

**Issue by daltonos** [seizonsenryaku/HayaiLauncher#18]
search/selection mode:
show magnifying lens icon when there's no search going on;
and when no items have been found in search. (this includes the state of when the softkeyboard is either hidden or visible);
pressing the action button in this mode should select (highlight) the text in the search box if there's any.

launch mode:
show launch icon on the button when an item has been found in the search;
when user taps button, first app in the list should be launched.

**Comment by daltonos** [comment]
suggestion for launch icon : https://www.google.com/design/icons/index.html#ic_play_arrow

**Comment by seizonsenryaku** [comment]
I think this was a suggestion for a previously proposed UI. I'm closing this for now.
