### ISSUE TITLE
Auto-select text onResume

### ISSUE THREAD

**Issue by daltonos** [seizonsenryaku/HayaiLauncher#2]
Text should be auto selected when user goes back to app

**Comment by seizonsenryaku** [comment]
Fixed in 6197361674d0b3f2e5a3c07c77efd7dbf7dc8a0d

**Comment by seizonsenryaku** [comment]
I'm reopening this, it seems that the text is auto selected only when the edit view loses focus and that doesn't happen as often as I thought it would.

**Comment by seizonsenryaku** [comment]
I think this is ok with 8149b1e4e4d23985c0044685d8a42d8a2013bcf8
