### ISSUE TITLE
Strings app_item_bottom_once

### ISSUE THREAD

**Issue by RyDroid** [seizonsenryaku/HayaiLauncher#35]
Hi.

"app_item_bottom_once" contains a "%d". I do not develop for Android, but I suppose that it is a format for an integer like with printf function of C. I understand the need for "app_item_bottom_several", but I don't for "app_item_bottom_once". If there is no explanation, I think that "%d" should be replaced by "1" in "app_item_bottom_once", as it is less confusing especially for potential non programmer translators.

Regards.

**Comment by seizonsenryaku** [comment]
Both strings aren't used any more, I'll remove them later, thanks!

**Comment by RyDroid** [comment]
Ok.
