### ISSUE TITLE
Is this meant to be a clone of Ligi's FAST & FASTER?

### ISSUE THREAD

**Issue by TPS** [seizonsenryaku/HayaiLauncher#38]
https://github.com/ligi/FAST for a very mature codebase.…

**Comment by seizonsenryaku** [comment]
This isn't meant to be a clone of anything, I had never heard of that project.

**Comment by TPS** [comment]
Great minds think alike & all that, then.… ☺

**Comment by daltonos** [comment]
Great minds think alike, stupid ones do too , even more often haha. But anyways, I'm just being silly.

hayai does look a lot like the project you've mentioned. But this is actually a utility commonly found in many platforms, so I guess we've cloned Windows start menu search feature for example.

I'm expecting these tools to be a little more than just a way to search apps in the future though.
