### ISSUE TITLE
Not recognised as a launcher.

### ISSUE THREAD

**Issue by pypcz** [seizonsenryaku/HayaiLauncher#39]
On lollipop there is no way to set this app as a launcher. Android version 5.0.2 on Moto G 2nd gen.

**Comment by pypcz** [comment]
After lurking on github for a bit I've noticed that this functiinality was present but removed later on. If this is a feature and not a bug feel free to delete this issue but if you want to hear my personal opinion on that matter: what's the point of developing a launcher that can't be used as a launcher?

**Comment by seizonsenryaku** [comment]
Thanks for your feedback.
I predicted that if I let that option a lot of people would try to use it by default and not realize that it can be used without replacing your home launcher.
I will add back that option in the next release.

**Comment by seizonsenryaku** [comment]
Fixed in release v1.1.5.
