### ISSUE TITLE
Toggle autofocus / showKeyboard

### ISSUE THREAD

**Issue by aevare** [seizonsenryaku/HayaiLauncher#41]
I think it would be nice to be able to toggle if search should be auto focused, that is opens the keyboard right away.
First thing I did was go into settings and look for that checkbox.

I don't think I'm the only one who just uses the list, especially since the last used apps are on top.

**Comment by realdmitchell** [comment]
I too please request this feature. Thanks

**Comment by pypcz** [comment]
I'm not really using the search feature so option to hide the keyboard by default would be nice.

**Comment by seizonsenryaku** [comment]
Done, please wait until the next release.

**Comment by seizonsenryaku** [comment]
This is in v1.1.6, it is available now on github and should be available on other channels soon.
