### ISSUE TITLE
Not listing apps from SD card

### ISSUE THREAD

**Issue by IBPX** [seizonsenryaku/HayaiLauncher#47]
Hayai Launcher is not displaying any apps that have been moved to my SD card. I moved VLC to SD and it is no longer listed. I thought I may have accidentally uninstalled it or something like that, but I have checked and it seems none of the other SD card apps show up either.

I am using Hayai Launcher 1.1.6.

(By the way: Hayai Launcher is awesome! It's the only launcher I've found that suits me.)

**Comment by pizzadude** [comment]
I have this issue too, for now I just force close Hayai Launcher and it will re-open and show the SD card apps.

**Comment by seizonsenryaku** [comment]
You can probably make the missing apps appear if you toggle/untoggle the setting to load app icons, it's probably easier to you than doing a force close.
