### ISSUE TITLE
[Polish] Bug fixes in language

### ISSUE THREAD

**Issue by fervi** [seizonsenryaku/HayaiLauncher#62]
Hayai today Launcher installed with Android and noticed (unfortunately) some minor language errors (in Polish)
1) "Zarządzaj applikacjami" should be "Zarządzaj aplikacjami"
2) "Wyłącz ładowanie ikonów" to "Wyłącz ładowanie ikon"

Thank you for good launcher :)
Fervi

**Comment by fervi** [comment]
3) "Informacje Applikacji" to "Informacje aplikacji"

**Comment by twckr** [comment]
Thank you for your help.
I just commited these changes.

**Comment by seizonsenryaku** [comment]
I've merged the pull request, this should be fixed in the next release.
